import { Inter } from 'next/font/google';

import { ToastsContainer } from '@/components/ToastsContainer';
import { ToastsProvider } from '@/contexts/toasts';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: './icon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <ToastsProvider>
        <body className={inter.className + ' overflow-x-hidden'}>
          {children}
          <ToastsContainer />
        </body>
      </ToastsProvider>
    </html>
  );
}
